### ISSUE TITLE
lets make into a class

### ISSUE THREAD

**Issue by nima64** [comcsclub/double-joint-arm#1]
class Stepper {               // The class
public:                       // Access specifier
  int currSteps;          // Attribute (int variable)
  Stepper(){
    currSteps = 0;
  }
  moveSteps(int steps) {
    for (int I = 0; I < steps; I++) {
      this->currSteps++;
      digitalWrite(3, HIGH);
      delayMicroseconds(700);
      digitalWrite(3, LOW);
      delayMicroseconds(700);
    }
  };
} 

Stepper mystepper();
// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);
  mystepper.moveSteps(200);
}

// the loop routine runs over and over again forever:
void loop() {
  // read the input on analog pin 0:
  int sensorValue = analogRead(A0);
  Serial.println(sensorValue);
  delay(1);  // delay in between reads for stability
}

**Comment by Zammmn** [comment]
class StepperS { // The class
  public: // Access specifier
    int currSteps; // Attribute (int variable)
    StepperS() {
      currSteps = 0;
      pinMode(2, OUTPUT);
      pinMode(3, OUTPUT);
    }
    void moveSteps(int steps) {
    digitalWrite(2, HIGH);

      for (int I = 0; I < steps; I++) {

        this->currSteps++;
        digitalWrite(3, HIGH);
        delayMicroseconds(700);
        digitalWrite(3, LOW);
        delayMicroseconds(700);
      }
    };
};

StepperS mystepper;
// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);
  mystepper.moveSteps(200);
}

// the loop routine runs over and over again forever:
void loop() {
  // read the input on analog pin 0:
  int sensorValue = analogRead(A0);
  Serial.println(sensorValue);
  delay(1); // delay in between reads for stability
}

**Comment by Zammmn** [comment]
```

class StepperS { // The class
  public: // Access specifier
    int currSteps; // Attribute (int variable)
    StepperS() {
      currSteps = 0;
      pinMode(2, OUTPUT);
      pinMode(3, OUTPUT);
    }
    void moveSteps(int steps) {
    digitalWrite(2, HIGH);

      for (int I = 0; I < steps; I++) {

        this->currSteps++;
        digitalWrite(3, HIGH);
        delayMicroseconds(700);
        digitalWrite(3, LOW);
        delayMicroseconds(700);
      }
    };
};

StepperS mystepper;
// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);
  mystepper.moveSteps(200);
}

// the loop routine runs over and over again forever:
void loop() {
  // read the input on analog pin 0:
  int sensorValue = analogRead(A0);
  Serial.println(sensorValue);
  delay(1); // delay in between reads for stability
}


```
